In [42]:
from sklearn import svm
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.model_selection import StratifiedKFold, GridSearchCV, cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

# Data Processing

In this section, we cleaned the data by dropping NA. Also, we dropped column REP, county_name, and State. Because the unit of each column is different, we decide to scale each column.

In [43]:
train = pd.read_csv('training_data.csv')
train.drop(columns = ['Unnamed: 0'], inplace = True)
train.dropna(inplace = True)

In [44]:
train

,REP,DEM,Registerd,county_name,State,% age 25-34,% age 35-44,% age 45-54,% age 55-64,% age 65 or older,...,Average HH size,Median gross rent,Median value of an owner-occupied home,Median HH income,Median owner cost burden,Median renter cost burden,% Asian,% Black,% Hispanic,% White
0,0.646619,0.353381,14449,Abbeville,SC,10.288667,10.517500,11.790333,16.543667,24.078000,...,2.502167,728.833333,95739.999994,39557.233334,15.391667,33.148333,1.037333,9.143500,3.617500,86.376667
1,0.805878,0.194122,28039,Acadia,LA,14.357708,12.211417,12.420708,12.759250,13.154000,...,2.827750,667.325000,118608.333330,49745.220833,12.301250,26.236250,0.387383,17.377533,2.416433,79.292550
2,0.547582,0.452418,16750,Accomack,VA,11.056632,11.274000,13.029625,16.301854,21.739076,...,2.373333,797.656250,152720.486112,40916.204861,16.405556,28.705208,3.330545,32.345016,6.887462,58.932408
3,0.520220,0.479780,251238,Ada,ID,13.846994,13.671397,13.513508,12.722110,14.538925,...,2.534280,1041.757567,258447.737760,65698.628093,17.986236,27.683560,1.134933,0.454400,3.525526,93.455696
4,0.709042,0.290958,4114,Adair,IA,10.295694,10.963889,12.862500,16.609722,20.438611,...,2.269861,657.500000,114511.111117,57052.472222,15.975000,23.056944,1.824444,3.026111,9.036944,89.092500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2884,0.532717,0.467283,65609,Yuma,AZ,11.690674,11.913663,10.508008,11.467101,17.912618,...,2.724683,744.475000,110821.416670,43137.655834,16.539417,29.529167,0.143000,1.653917,29.900750,90.843000
2885,0.841042,0.158958,4800,Yuma,CO,11.804048,10.887619,12.432619,12.498810,17.883333,...,3.126667,757.547619,171045.238100,49239.690476,14.752381,26.345238,2.726905,6.264708,18.185628,78.008528
2886,0.527518,0.472482,3852,Zapata,TX,11.562222,10.762222,10.167778,8.155556,12.602222,...,2.768889,494.777778,66300.000000,29566.888890,13.233333,32.866667,0.379653,1.075947,62.138507,87.103829
2887,0.342214,0.657786,4354,Zavala,TX,11.677222,12.371111,12.193889,10.218333,12.681667,...,3.380000,601.444444,49644.444443,25880.777777,13.372222,32.572222,0.068333,0.246667,40.903333,91.505000
2888,0.456497,0.543503,885,Ziebach,SD,12.006667,14.240000,10.030000,10.790000,8.396667,...,2.720000,696.000000,98033.333333,42973.000000,14.633333,27.700000,0.288889,0.280000,1.227778,93.937778

In [45]:
train.columns

Index(['REP', 'DEM', 'Registerd', 'county_name', 'State', '% age 25-34',
       '% age 35-44', '% age 45-54', '% age 55-64', '% age 65 or older',
       'Median age ', '% Bachelor's', '% HS diploma', '% less than HS diploma',
       '% post grad', '% college', 'Average HH size', 'Median gross rent',
       'Median value of an owner-occupied home', 'Median HH income',
       'Median owner cost burden', 'Median renter cost burden', '% Asian',
       '% Black', '% Hispanic', '% White'],
      dtype='object')

In [46]:
train_cleaned = train.drop(columns = ['REP', 'county_name', 'State','Registerd'])

In [47]:
y = train_cleaned['DEM']
x = train_cleaned.drop(columns = ['DEM'])

scaler = StandardScaler()
x = scaler.fit_transform(x)

In [48]:
x

array([[-0.36196025, -0.56444488, -1.04359506, ...,  0.05276503,
        -0.42284274,  0.20431043],
       [ 1.5950124 ,  0.59163096, -0.61568418, ...,  0.74132249,
        -0.51739198, -0.31134015],
       [ 0.00738643, -0.04814358, -0.20233963, ...,  1.99295352,
        -0.16542785, -1.79334834],
       ...,
       [ 0.25054598, -0.39742518, -2.14501751, ..., -0.62187081,
         4.18399306,  0.25724035],
       [ 0.3058543 ,  0.70062032, -0.76965365, ..., -0.691218  ,
         2.51233765,  0.57760016],
       [ 0.46429794,  1.9761124 , -2.23854376, ..., -0.68843055,
        -0.61096421,  0.75468128]])

# Hyper Parameter Tunning

In [32]:
svm_mod = svm.SVR()
GS_SVM =  GridSearchCV(svm_mod, param_grid = {'C':np.linspace(0.01, 10),'epsilon':np.linspace(0.01, 0.2, 10)}, scoring = 'neg_mean_squared_error', cv = 10)

In [33]:
GS_SVM.fit(x,y)

GridSearchCV(cv=10, estimator=SVR(),
             param_grid={'C': array([ 0.01      ,  0.21387755,  0.4177551 ,  0.62163265,  0.8255102 ,
        1.02938776,  1.23326531,  1.43714286,  1.64102041,  1.84489796,
        2.04877551,  2.25265306,  2.45653061,  2.66040816,  2.86428571,
        3.06816327,  3.27204082,  3.47591837,  3.67979592,  3.88367347,
        4.08755102,  4.29142857,  4.49530612,  4.69918367,  4.90306122,
        5.10693878,  5.31081633,  5.5...
        6.12632653,  6.33020408,  6.53408163,  6.73795918,  6.94183673,
        7.14571429,  7.34959184,  7.55346939,  7.75734694,  7.96122449,
        8.16510204,  8.36897959,  8.57285714,  8.77673469,  8.98061224,
        9.1844898 ,  9.38836735,  9.5922449 ,  9.79612245, 10.        ]),
                         'epsilon': array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ])},
             scoring='neg_mean_squared_error')

In [34]:
print(GS_SVM.best_params_)
print(GS_SVM.best_score_)

{'C': 0.6216326530612245, 'epsilon': 0.02}
-0.008111319663869073

In [49]:
np.mean(cross_val_score(svm.SVR(C=0.6,epsilon=0.02),x,y,scoring = 'neg_mean_squared_error',cv=10))

-0.008108143157443206

# Test Data Processing

In [50]:
test = pd.read_csv('Georgia_data.csv')
test.drop(columns = ['Unnamed: 0'], inplace = True)
test.dropna(inplace = True)

In [51]:
test_cleaned = test.drop(columns = ['REP', 'county_name', 'State','Registerd'])
y_test = test_cleaned['DEM']
x_test = test_cleaned.drop(columns = ['DEM'])

scaler = StandardScaler()
x_test = scaler.fit_transform(x_test)

In [52]:
test_cleaned

,DEM,% age 25-34,% age 35-44,% age 45-54,% age 55-64,% age 65 or older,Median age,% Bachelor's,% HS diploma,% less than HS diploma,...,Average HH size,Median gross rent,Median value of an owner-occupied home,Median HH income,Median owner cost burden,Median renter cost burden,% Asian,% Black,% Hispanic,% White
0,0.214208,11.400556,11.901389,13.395556,13.177778,18.195278,39.777778,6.354167,39.500833,22.908889,...,2.528056,548.916667,78838.888890,43627.500000,14.741667,20.922222,1.646803,44.159641,4.873179,50.830957
1,0.264000,13.655667,12.473667,13.176833,10.997333,12.743833,34.366667,6.289167,39.094333,26.166667,...,2.704833,528.566667,70453.333333,37215.183333,14.826667,26.663333,0.482333,27.713778,7.339556,65.746000
2,0.134611,12.695556,12.570000,12.247778,13.605556,16.566667,38.777778,7.003333,40.713333,20.816667,...,2.693333,558.111111,75433.333330,39905.777780,14.911111,26.011111,0.120000,43.040000,8.930000,51.260000
3,0.420917,11.045000,9.170000,13.500000,14.585000,25.120000,45.500000,8.285000,38.310000,20.320000,...,2.910000,484.500000,76250.000000,36886.500000,15.850000,20.500000,0.422000,0.824000,3.114000,95.730000
4,0.506568,12.208462,8.980769,11.977308,13.556538,14.799231,33.730769,6.650000,38.808846,25.165385,...,2.957692,707.461538,75292.307700,33768.769230,20.192308,34.265385,0.526000,73.831000,0.754500,22.439000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,0.293891,11.918275,12.826799,14.576689,12.201471,14.414238,38.622751,11.172837,30.326022,22.725190,...,2.683434,712.023148,140574.735450,53658.273413,15.779894,24.811415,1.421444,32.972481,3.367148,62.204815
155,0.264012,12.102292,13.340583,12.061125,14.859542,18.154583,40.245833,6.940000,44.166333,20.269500,...,2.609250,535.341667,76447.916665,38714.433332,14.886250,32.645417,1.405179,32.085625,4.375536,63.535446
156,0.433360,8.547056,10.156389,15.254333,14.503333,22.463111,45.311111,6.605500,43.608222,22.344722,...,2.552444,634.938889,83564.444443,36960.933333,17.951111,29.167778,0.543611,26.038056,4.449722,68.610278
157,0.437856,9.680833,12.213333,12.488333,16.668750,20.481667,46.708333,6.940833,53.892083,17.570000,...,2.669583,624.583333,78987.500000,38565.333335,13.150000,34.229167,3.010643,26.031857,8.874429,65.874857
158,0.259733,11.787778,11.143472,14.054444,13.900139,18.634583,41.722222,6.121944,39.811806,22.951667,...,2.895833,654.361111,89265.277778,45253.958333,16.154167,29.534722,1.986675,26.204897,6.706294,68.103706

# Test Best Model

In [59]:
svm_mod = svm.SVR(C=0.6,epsilon=0.02)
svm_mod.fit(x,y)

SVR(C=0.6, epsilon=0.02)

In [60]:
Y_pred=svm_mod.predict(x_test)
np.mean((Y_pred - y_test)**2)

0.021268508883475395

In [61]:
Y_pred

array([0.2130422 , 0.18041564, 0.24663249, 0.19091359, 0.79182452,
       0.23130374, 0.32320259, 0.27095523, 0.23878974, 0.22817773,
       0.52015534, 0.22843348, 0.22166863, 0.48518732, 0.24716907,
       0.44949615, 0.25942468, 0.28239662, 0.19626275, 0.26513289,
       0.24051062, 0.31949619, 0.21634612, 0.34993274, 0.55765277,
       0.45347531, 0.21351071, 0.40256107, 0.60567942, 0.23477472,
       0.53581772, 0.5444111 , 0.54216226, 0.25057924, 0.15358023,
       0.30386863, 0.31313485, 0.37083805, 0.29492657, 0.29776797,
       0.24657823, 0.35201391, 0.85295625, 0.22078162, 0.36134795,
       0.44968948, 0.42003768, 0.31751063, 0.17675704, 0.28037952,
       0.28732021, 0.14737967, 0.16855877, 0.18502831, 0.30525212,
       0.37081991, 0.2423471 , 0.4554727 , 0.23664401, 0.81318416,
       0.24215196, 0.50135747, 0.39357673, 0.24445585, 0.20650104,
       0.31148575, 0.54799528, 0.32369254, 0.31532756, 0.30167644,
       0.27988271, 0.33524351, 0.2295945 , 0.27193837, 0.47419384,
       0.32523283, 0.19162187, 0.28996329, 0.4422336 , 0.22929941,
       0.20531677, 0.27627154, 0.16046623, 0.28058305, 0.34148556,
       0.21195168, 0.31803131, 0.31784594, 0.23654275, 0.30117535,
       0.35080414, 0.40524815, 0.4834397 , 0.46730009, 0.23574129,
       0.3418041 , 0.35702825, 0.33405361, 0.36642516, 0.26790092,
       0.56686129, 0.31206466, 0.17262915, 0.16744204, 0.17643791,
       0.5390005 , 0.45409675, 0.45030334, 0.28995424, 0.37516344,
       0.3146192 , 0.21766589, 0.23570705, 0.27399623, 0.30545053,
       0.19121192, 0.32432543, 0.30208783, 0.40049852, 0.18415804,
       0.56105963, 0.46119932, 0.28910445, 0.20470077, 0.20298387,
       0.40414477, 0.30069221, 0.39997383, 0.49514533, 0.33710372,
       0.20927069, 0.20820475, 0.39147436, 0.34110584, 0.14790167,
       0.39984924, 0.34539048, 0.20154499, 0.41678621, 0.22364727,
       0.44470451, 0.31733366, 0.43455328, 0.30233555, 0.28850028,
       0.23239932, 0.41973076, 0.25558404, 0.57823844, 0.36883638,
       0.19752217, 0.27629367, 0.24554836, 0.27482587, 0.19137068,
       0.27435347, 0.30032426, 0.26051458, 0.23864529])

In [ ]:
result = pd.DataFrame()
result['Potential'] = test['Registerd']*Y_pred
result['Real'] = test['Registerd']*y_test
result['county'] = test['county_name']
result['Difference'] = result['Potential'] - result['Real']
#sum(result['Difference'] >= 0)
#result

In [ ]:
result.to_csv("result.csv",index=False)